name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Determine image tag
      id: timestamp
      run: echo "::set-output name=value::$(date +%s)"

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pauljoy2000/docker-img:${{ steps.timestamp.outputs.value }}

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push pauljoy2000/docker-img:${{ steps.timestamp.outputs.value }}
